name: Build Tauri App

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치 이름

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          args: build

      # (Optional) 결과물 업로드
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-build-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/