# .github/workflows/build.yml
name: Build Tauri and Web App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest] # 필요시 windows-latest 추가 가능
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Build web frontend
        run: pnpm build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.4.3
        with:
          tagName: tauri-build-${{ matrix.platform }}
          releaseName: "Build - ${{ matrix.platform }}"
          args: --target release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: tauri-build-${{ matrix.platform }}
          path: src-tauri/target/release/bundle